Switch to Typescript

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -26,7 +26,7 @@ jobs:
           node-version: ${{ matrix.node-version }}
           cache: yarn
       - name: install with jest@${{ matrix.jest-version }}
-        run: yarn add --dev jest@${{ matrix.jest-version }} babel-jest@${{ matrix.jest-version }} @types/jest@${{ matrix.jest-version }}
+        run: yarn add --dev jest@${{ matrix.jest-version }} ts-jest@${{ matrix.jest-version }} @types/jest@${{ matrix.jest-version }}
       - run: yarn test:coverage
       - uses: codecov/codecov-action@v5
         if: ${{ always() }}
@@ -63,6 +63,15 @@ jobs:
       - run: yarn build
       - run: yarn lint
       - run: yarn typecheck
+      - run: |
+          js_files=$(find src test -type f -name '*.js')
+          if [ -n "$js_files" ]; then
+            echo "::error::Found disallowed .js files. Please convert them to .ts:"
+            echo "$js_files"
+            exit 1
+          else
+            echo "No disallowed .js files found in src/ or test/. Check passed."
+          fi
   release:
     name: Run publish action
     if: ${{ github.event_name == 'push' && (github.event.ref == 'refs/heads/main' || github.event.ref == 'refs/heads/next') }}
